/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ButtonFieldRequest
 */
export interface ButtonFieldRequest {
  /**
   *
   * @type {string}
   * @memberof ButtonFieldRequest
   */
  text: string
  /**
   *
   * @type {string}
   * @memberof ButtonFieldRequest
   */
  themeState: string
}

export function ButtonFieldRequestFromJSON(json: any): ButtonFieldRequest {
  return ButtonFieldRequestFromJSONTyped(json, false)
}

export function ButtonFieldRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ButtonFieldRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    text: json['text'],
    themeState: json['theme_state'],
  }
}

export function ButtonFieldRequestToJSON(
  value?: ButtonFieldRequest | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    text: value.text,
    theme_state: value.themeState,
  }
}
