/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  ButtonFieldRequest,
  ButtonFieldRequestFromJSON,
  ButtonFieldRequestFromJSONTyped,
  ButtonFieldRequestToJSON,
} from './'

/**
 * Base serializer for all actions.
 * @export
 * @interface CancelActionRequest
 */
export interface CancelActionRequest {
  /**
   *
   * @type {ButtonFieldRequest}
   * @memberof CancelActionRequest
   */
  button?: ButtonFieldRequest
  /**
   *
   * @type {string}
   * @memberof CancelActionRequest
   */
  subscriptionId?: string
}

export function CancelActionRequestFromJSON(json: any): CancelActionRequest {
  return CancelActionRequestFromJSONTyped(json, false)
}

export function CancelActionRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CancelActionRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    button: !exists(json, 'button')
      ? undefined
      : ButtonFieldRequestFromJSON(json['button']),
    subscriptionId: !exists(json, 'subscription_id')
      ? undefined
      : json['subscription_id'],
  }
}

export function CancelActionRequestToJSON(
  value?: CancelActionRequest | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    button: ButtonFieldRequestToJSON(value.button),
    subscription_id: value.subscriptionId,
  }
}
