/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface ClientSecret
 */
export interface ClientSecret {
  /**
   *
   * @type {string}
   * @memberof ClientSecret
   */
  clientSecret: string
}

export function ClientSecretFromJSON(json: any): ClientSecret {
  return ClientSecretFromJSONTyped(json, false)
}

export function ClientSecretFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ClientSecret {
  if (json === undefined || json === null) {
    return json
  }
  return {
    clientSecret: json['client_secret'],
  }
}

export function ClientSecretToJSON(value?: ClientSecret | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    client_secret: value.clientSecret,
  }
}
