/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CognitoAuthConfig
 */
export interface CognitoAuthConfig {
  /**
   *
   * @type {string}
   * @memberof CognitoAuthConfig
   */
  readonly id: string
  /**
   *
   * @type {string}
   * @memberof CognitoAuthConfig
   */
  providerId: string
  /**
   *
   * @type {string}
   * @memberof CognitoAuthConfig
   */
  region: string
  /**
   *
   * @type {string}
   * @memberof CognitoAuthConfig
   */
  userPoolId: string
  /**
   *
   * @type {string}
   * @memberof CognitoAuthConfig
   */
  appClientId: string
}

export function CognitoAuthConfigFromJSON(json: any): CognitoAuthConfig {
  return CognitoAuthConfigFromJSONTyped(json, false)
}

export function CognitoAuthConfigFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CognitoAuthConfig {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: json['id'],
    providerId: json['provider_id'],
    region: json['region'],
    userPoolId: json['user_pool_id'],
    appClientId: json['app_client_id'],
  }
}

export function CognitoAuthConfigToJSON(value?: CognitoAuthConfig | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    provider_id: value.providerId,
    region: value.region,
    user_pool_id: value.userPoolId,
    app_client_id: value.appClientId,
  }
}
