/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  IdentityRequest,
  IdentityRequestFromJSON,
  IdentityRequestFromJSONTyped,
  IdentityRequestToJSON,
} from './'

/**
 *
 * @export
 * @interface CreateCustomerRequest
 */
export interface CreateCustomerRequest {
  /**
   *
   * @type {IdentityRequest}
   * @memberof CreateCustomerRequest
   */
  identity: IdentityRequest
  /**
   *
   * @type {string}
   * @memberof CreateCustomerRequest
   */
  sourceId?: string
}

export function CreateCustomerRequestFromJSON(
  json: any
): CreateCustomerRequest {
  return CreateCustomerRequestFromJSONTyped(json, false)
}

export function CreateCustomerRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateCustomerRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    identity: IdentityRequestFromJSON(json['identity']),
    sourceId: !exists(json, 'source_id') ? undefined : json['source_id'],
  }
}

export function CreateCustomerRequestToJSON(
  value?: CreateCustomerRequest | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    identity: IdentityRequestToJSON(value.identity),
    source_id: value.sourceId,
  }
}
