/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import { OpEnum, OpEnumFromJSON, OpEnumFromJSONTyped, OpEnumToJSON } from './'

/**
 *
 * @export
 * @interface CreateUsageRequest
 */
export interface CreateUsageRequest {
  /**
   *
   * @type {string}
   * @memberof CreateUsageRequest
   */
  idempotencyKey?: string | null
  /**
   *
   * @type {string}
   * @memberof CreateUsageRequest
   */
  slug: string
  /**
   *
   * @type {OpEnum}
   * @memberof CreateUsageRequest
   */
  op: OpEnum
  /**
   *
   * @type {number}
   * @memberof CreateUsageRequest
   */
  value?: number
  /**
   *
   * @type {Date}
   * @memberof CreateUsageRequest
   */
  occurredAt?: Date
}

export function CreateUsageRequestFromJSON(json: any): CreateUsageRequest {
  return CreateUsageRequestFromJSONTyped(json, false)
}

export function CreateUsageRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateUsageRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    idempotencyKey: !exists(json, 'idempotency_key')
      ? undefined
      : json['idempotency_key'],
    slug: json['slug'],
    op: OpEnumFromJSON(json['op']),
    value: !exists(json, 'value') ? undefined : json['value'],
    occurredAt: !exists(json, 'occurred_at')
      ? undefined
      : new Date(json['occurred_at']),
  }
}

export function CreateUsageRequestToJSON(
  value?: CreateUsageRequest | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    idempotency_key: value.idempotencyKey,
    slug: value.slug,
    op: OpEnumToJSON(value.op),
    value: value.value,
    occurred_at:
      value.occurredAt === undefined
        ? undefined
        : value.occurredAt.toISOString(),
  }
}
