/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CreateSubscribeIntentRequest
 */
export interface CreateSubscribeIntentRequest {
  /**
   *
   * @type {string}
   * @memberof CreateSubscribeIntentRequest
   */
  teamId: string
  /**
   *
   * @type {string}
   * @memberof CreateSubscribeIntentRequest
   */
  planOptionId: string
  /**
   *
   * @type {string}
   * @memberof CreateSubscribeIntentRequest
   */
  paymentMethodId?: string
}

export function CreateSubscribeIntentRequestFromJSON(
  json: any
): CreateSubscribeIntentRequest {
  return CreateSubscribeIntentRequestFromJSONTyped(json, false)
}

export function CreateSubscribeIntentRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CreateSubscribeIntentRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    teamId: json['team_id'],
    planOptionId: json['plan_option_id'],
    paymentMethodId: !exists(json, 'payment_method_id')
      ? undefined
      : json['payment_method_id'],
  }
}

export function CreateSubscribeIntentRequestToJSON(
  value?: CreateSubscribeIntentRequest | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    team_id: value.teamId,
    plan_option_id: value.planOptionId,
    payment_method_id: value.paymentMethodId,
  }
}
