/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface CustomerIntentRequest
 */
export interface CustomerIntentRequest {
  /**
   *
   * @type {string}
   * @memberof CustomerIntentRequest
   */
  planId: string
  /**
   *
   * @type {string}
   * @memberof CustomerIntentRequest
   */
  teamId: string
}

export function CustomerIntentRequestFromJSON(
  json: any
): CustomerIntentRequest {
  return CustomerIntentRequestFromJSONTyped(json, false)
}

export function CustomerIntentRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CustomerIntentRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    planId: json['plan_id'],
    teamId: json['team_id'],
  }
}

export function CustomerIntentRequestToJSON(
  value?: CustomerIntentRequest | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    plan_id: value.planId,
    team_id: value.teamId,
  }
}
