/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface FronteggAuthConfig
 */
export interface FronteggAuthConfig {
  /**
   *
   * @type {string}
   * @memberof FronteggAuthConfig
   */
  readonly id: string
  /**
   *
   * @type {string}
   * @memberof FronteggAuthConfig
   */
  providerId: string
  /**
   *
   * @type {string}
   * @memberof FronteggAuthConfig
   */
  publicKey: string
}

export function FronteggAuthConfigFromJSON(json: any): FronteggAuthConfig {
  return FronteggAuthConfigFromJSONTyped(json, false)
}

export function FronteggAuthConfigFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): FronteggAuthConfig {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: json['id'],
    providerId: json['provider_id'],
    publicKey: json['public_key'],
  }
}

export function FronteggAuthConfigToJSON(
  value?: FronteggAuthConfig | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    provider_id: value.providerId,
    public_key: value.publicKey,
  }
}
