/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface FronteggAuthConfigRequest
 */
export interface FronteggAuthConfigRequest {
  /**
   *
   * @type {string}
   * @memberof FronteggAuthConfigRequest
   */
  providerId: string
  /**
   *
   * @type {string}
   * @memberof FronteggAuthConfigRequest
   */
  publicKey: string
}

export function FronteggAuthConfigRequestFromJSON(
  json: any
): FronteggAuthConfigRequest {
  return FronteggAuthConfigRequestFromJSONTyped(json, false)
}

export function FronteggAuthConfigRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): FronteggAuthConfigRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    providerId: json['provider_id'],
    publicKey: json['public_key'],
  }
}

export function FronteggAuthConfigRequestToJSON(
  value?: FronteggAuthConfigRequest | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    provider_id: value.providerId,
    public_key: value.publicKey,
  }
}
