/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface IdentityRequest
 */
export interface IdentityRequest {
  /**
   *
   * @type {string}
   * @memberof IdentityRequest
   */
  email: string
}

export function IdentityRequestFromJSON(json: any): IdentityRequest {
  return IdentityRequestFromJSONTyped(json, false)
}

export function IdentityRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): IdentityRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    email: json['email'],
  }
}

export function IdentityRequestToJSON(value?: IdentityRequest | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    email: value.email,
  }
}
