/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface InnerError
 */
export interface InnerError {
  /**
   *
   * @type {Array<{ [key: string]: any; }>}
   * @memberof InnerError
   */
  nonFieldErrors: Array<{ [key: string]: any }>
  /**
   *
   * @type {Array<{ [key: string]: any; }>}
   * @memberof InnerError
   */
  fieldErrors: Array<{ [key: string]: any }>
}

export function InnerErrorFromJSON(json: any): InnerError {
  return InnerErrorFromJSONTyped(json, false)
}

export function InnerErrorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InnerError {
  if (json === undefined || json === null) {
    return json
  }
  return {
    nonFieldErrors: json['non_field_errors'],
    fieldErrors: json['field_errors'],
  }
}

export function InnerErrorToJSON(value?: InnerError | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    non_field_errors: value.nonFieldErrors,
    field_errors: value.fieldErrors,
  }
}
