/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  BillingPeriodEnum,
  BillingPeriodEnumFromJSON,
  BillingPeriodEnumFromJSONTyped,
  BillingPeriodEnumToJSON,
  StateEnum,
  StateEnumFromJSON,
  StateEnumFromJSONTyped,
  StateEnumToJSON,
} from './'

/**
 *
 * @export
 * @interface InvoiceRequest
 */
export interface InvoiceRequest {
  /**
   *
   * @type {BillingPeriodEnum}
   * @memberof InvoiceRequest
   */
  billingPeriod?: BillingPeriodEnum
  /**
   *
   * @type {string}
   * @memberof InvoiceRequest
   */
  planName?: string
  /**
   *
   * @type {StateEnum}
   * @memberof InvoiceRequest
   */
  state: StateEnum
  /**
   *
   * @type {string}
   * @memberof InvoiceRequest
   */
  stripePaymentId?: string | null
}

export function InvoiceRequestFromJSON(json: any): InvoiceRequest {
  return InvoiceRequestFromJSONTyped(json, false)
}

export function InvoiceRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): InvoiceRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    billingPeriod: !exists(json, 'billing_period')
      ? undefined
      : BillingPeriodEnumFromJSON(json['billing_period']),
    planName: !exists(json, 'plan_name') ? undefined : json['plan_name'],
    state: StateEnumFromJSON(json['state']),
    stripePaymentId: !exists(json, 'stripe_payment_id')
      ? undefined
      : json['stripe_payment_id'],
  }
}

export function InvoiceRequestToJSON(value?: InvoiceRequest | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    billing_period: BillingPeriodEnumToJSON(value.billingPeriod),
    plan_name: value.planName,
    state: StateEnumToJSON(value.state),
    stripe_payment_id: value.stripePaymentId,
  }
}
