/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  RoleEnum,
  RoleEnumFromJSON,
  RoleEnumFromJSONTyped,
  RoleEnumToJSON,
} from './'

/**
 *
 * @export
 * @interface Membership
 */
export interface Membership {
  /**
   *
   * @type {string}
   * @memberof Membership
   */
  readonly id: string
  /**
   *
   * @type {string}
   * @memberof Membership
   */
  readonly teamId: string
  /**
   *
   * @type {string}
   * @memberof Membership
   */
  readonly customerId: string
  /**
   *
   * @type {RoleEnum}
   * @memberof Membership
   */
  role: RoleEnum
  /**
   *
   * @type {string}
   * @memberof Membership
   */
  readonly email: string
}

export function MembershipFromJSON(json: any): Membership {
  return MembershipFromJSONTyped(json, false)
}

export function MembershipFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Membership {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: json['id'],
    teamId: json['team_id'],
    customerId: json['customer_id'],
    role: RoleEnumFromJSON(json['role']),
    email: json['email'],
  }
}

export function MembershipToJSON(value?: Membership | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    role: RoleEnumToJSON(value.role),
  }
}
