/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum OnSubscriptionEndEnum {
  Expire = 'expire',
  Renew = 'renew',
}

export function OnSubscriptionEndEnumFromJSON(
  json: any
): OnSubscriptionEndEnum {
  return OnSubscriptionEndEnumFromJSONTyped(json, false)
}

export function OnSubscriptionEndEnumFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): OnSubscriptionEndEnum {
  return json as OnSubscriptionEndEnum
}

export function OnSubscriptionEndEnumToJSON(
  value?: OnSubscriptionEndEnum | null
): any {
  return value as any
}
