/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  StripeCardPaymentMethod,
  StripeCardPaymentMethodFromJSON,
  StripeCardPaymentMethodFromJSONTyped,
  StripeCardPaymentMethodToJSON,
} from './'

/**
 *
 * @export
 * @interface PaginatedStripeCardPaymentMethodList
 */
export interface PaginatedStripeCardPaymentMethodList {
  /**
   *
   * @type {number}
   * @memberof PaginatedStripeCardPaymentMethodList
   */
  count?: number
  /**
   *
   * @type {string}
   * @memberof PaginatedStripeCardPaymentMethodList
   */
  next?: string | null
  /**
   *
   * @type {string}
   * @memberof PaginatedStripeCardPaymentMethodList
   */
  previous?: string | null
  /**
   *
   * @type {Array<StripeCardPaymentMethod>}
   * @memberof PaginatedStripeCardPaymentMethodList
   */
  results?: Array<StripeCardPaymentMethod>
}

export function PaginatedStripeCardPaymentMethodListFromJSON(
  json: any
): PaginatedStripeCardPaymentMethodList {
  return PaginatedStripeCardPaymentMethodListFromJSONTyped(json, false)
}

export function PaginatedStripeCardPaymentMethodListFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PaginatedStripeCardPaymentMethodList {
  if (json === undefined || json === null) {
    return json
  }
  return {
    count: !exists(json, 'count') ? undefined : json['count'],
    next: !exists(json, 'next') ? undefined : json['next'],
    previous: !exists(json, 'previous') ? undefined : json['previous'],
    results: !exists(json, 'results')
      ? undefined
      : (json['results'] as Array<any>).map(StripeCardPaymentMethodFromJSON),
  }
}

export function PaginatedStripeCardPaymentMethodListToJSON(
  value?: PaginatedStripeCardPaymentMethodList | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    count: value.count,
    next: value.next,
    previous: value.previous,
    results:
      value.results === undefined
        ? undefined
        : (value.results as Array<any>).map(StripeCardPaymentMethodToJSON),
  }
}
