/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  OnSubscriptionEndEnum,
  OnSubscriptionEndEnumFromJSON,
  OnSubscriptionEndEnumFromJSONTyped,
  OnSubscriptionEndEnumToJSON,
  SIInvoiceRequest,
  SIInvoiceRequestFromJSON,
  SIInvoiceRequestFromJSONTyped,
  SIInvoiceRequestToJSON,
} from './'

/**
 *
 * @export
 * @interface PatchedSubscribeIntentRequest
 */
export interface PatchedSubscribeIntentRequest {
  /**
   *
   * @type {string}
   * @memberof PatchedSubscribeIntentRequest
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof PatchedSubscribeIntentRequest
   */
  planOptionId?: string
  /**
   *
   * @type {SIInvoiceRequest}
   * @memberof PatchedSubscribeIntentRequest
   */
  invoice?: SIInvoiceRequest
  /**
   *
   * @type {number}
   * @memberof PatchedSubscribeIntentRequest
   */
  creditCents?: number
  /**
   *
   * @type {OnSubscriptionEndEnum}
   * @memberof PatchedSubscribeIntentRequest
   */
  onSubscriptionEnd?: OnSubscriptionEndEnum
  /**
   *
   * @type {number}
   * @memberof PatchedSubscribeIntentRequest
   */
  nextUpfrontBillInDays?: number
  /**
   *
   * @type {number}
   * @memberof PatchedSubscribeIntentRequest
   */
  nextMeterBillInDays?: number
  /**
   *
   * @type {number}
   * @memberof PatchedSubscribeIntentRequest
   */
  trialEndInDays?: number
}

export function PatchedSubscribeIntentRequestFromJSON(
  json: any
): PatchedSubscribeIntentRequest {
  return PatchedSubscribeIntentRequestFromJSONTyped(json, false)
}

export function PatchedSubscribeIntentRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PatchedSubscribeIntentRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    planOptionId: !exists(json, 'plan_option_id')
      ? undefined
      : json['plan_option_id'],
    invoice: !exists(json, 'invoice')
      ? undefined
      : SIInvoiceRequestFromJSON(json['invoice']),
    creditCents: !exists(json, 'credit_cents')
      ? undefined
      : json['credit_cents'],
    onSubscriptionEnd: !exists(json, 'on_subscription_end')
      ? undefined
      : OnSubscriptionEndEnumFromJSON(json['on_subscription_end']),
    nextUpfrontBillInDays: !exists(json, 'next_upfront_bill_in_days')
      ? undefined
      : json['next_upfront_bill_in_days'],
    nextMeterBillInDays: !exists(json, 'next_meter_bill_in_days')
      ? undefined
      : json['next_meter_bill_in_days'],
    trialEndInDays: !exists(json, 'trial_end_in_days')
      ? undefined
      : json['trial_end_in_days'],
  }
}

export function PatchedSubscribeIntentRequestToJSON(
  value?: PatchedSubscribeIntentRequest | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    plan_option_id: value.planOptionId,
    invoice: SIInvoiceRequestToJSON(value.invoice),
    credit_cents: value.creditCents,
    on_subscription_end: OnSubscriptionEndEnumToJSON(value.onSubscriptionEnd),
    next_upfront_bill_in_days: value.nextUpfrontBillInDays,
    next_meter_bill_in_days: value.nextMeterBillInDays,
    trial_end_in_days: value.trialEndInDays,
  }
}
