/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface PatchedUpdatePaymentMethodRequest
 */
export interface PatchedUpdatePaymentMethodRequest {
  /**
   *
   * @type {boolean}
   * @memberof PatchedUpdatePaymentMethodRequest
   */
  isDefault?: boolean | null
}

export function PatchedUpdatePaymentMethodRequestFromJSON(
  json: any
): PatchedUpdatePaymentMethodRequest {
  return PatchedUpdatePaymentMethodRequestFromJSONTyped(json, false)
}

export function PatchedUpdatePaymentMethodRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PatchedUpdatePaymentMethodRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    isDefault: !exists(json, 'is_default') ? undefined : json['is_default'],
  }
}

export function PatchedUpdatePaymentMethodRequestToJSON(
  value?: PatchedUpdatePaymentMethodRequest | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    is_default: value.isDefault,
  }
}
