/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  RoleEnum,
  RoleEnumFromJSON,
  RoleEnumFromJSONTyped,
  RoleEnumToJSON,
} from './'

/**
 *
 * @export
 * @interface PatchedMembershipRequest
 */
export interface PatchedMembershipRequest {
  /**
   *
   * @type {RoleEnum}
   * @memberof PatchedMembershipRequest
   */
  role?: RoleEnum
}

export function PatchedMembershipRequestFromJSON(
  json: any
): PatchedMembershipRequest {
  return PatchedMembershipRequestFromJSONTyped(json, false)
}

export function PatchedMembershipRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PatchedMembershipRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    role: !exists(json, 'role') ? undefined : RoleEnumFromJSON(json['role']),
  }
}

export function PatchedMembershipRequestToJSON(
  value?: PatchedMembershipRequest | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    role: RoleEnumToJSON(value.role),
  }
}
