/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface PatchedFronteggAuthConfigRequest
 */
export interface PatchedFronteggAuthConfigRequest {
  /**
   *
   * @type {string}
   * @memberof PatchedFronteggAuthConfigRequest
   */
  providerId?: string
  /**
   *
   * @type {string}
   * @memberof PatchedFronteggAuthConfigRequest
   */
  publicKey?: string
}

export function PatchedFronteggAuthConfigRequestFromJSON(
  json: any
): PatchedFronteggAuthConfigRequest {
  return PatchedFronteggAuthConfigRequestFromJSONTyped(json, false)
}

export function PatchedFronteggAuthConfigRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PatchedFronteggAuthConfigRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    providerId: !exists(json, 'provider_id') ? undefined : json['provider_id'],
    publicKey: !exists(json, 'public_key') ? undefined : json['public_key'],
  }
}

export function PatchedFronteggAuthConfigRequestToJSON(
  value?: PatchedFronteggAuthConfigRequest | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    provider_id: value.providerId,
    public_key: value.publicKey,
  }
}
