/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface PatchedCognitoAuthConfigRequest
 */
export interface PatchedCognitoAuthConfigRequest {
  /**
   *
   * @type {string}
   * @memberof PatchedCognitoAuthConfigRequest
   */
  providerId?: string
  /**
   *
   * @type {string}
   * @memberof PatchedCognitoAuthConfigRequest
   */
  region?: string
  /**
   *
   * @type {string}
   * @memberof PatchedCognitoAuthConfigRequest
   */
  userPoolId?: string
  /**
   *
   * @type {string}
   * @memberof PatchedCognitoAuthConfigRequest
   */
  appClientId?: string
}

export function PatchedCognitoAuthConfigRequestFromJSON(
  json: any
): PatchedCognitoAuthConfigRequest {
  return PatchedCognitoAuthConfigRequestFromJSONTyped(json, false)
}

export function PatchedCognitoAuthConfigRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PatchedCognitoAuthConfigRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    providerId: !exists(json, 'provider_id') ? undefined : json['provider_id'],
    region: !exists(json, 'region') ? undefined : json['region'],
    userPoolId: !exists(json, 'user_pool_id')
      ? undefined
      : json['user_pool_id'],
    appClientId: !exists(json, 'app_client_id')
      ? undefined
      : json['app_client_id'],
  }
}

export function PatchedCognitoAuthConfigRequestToJSON(
  value?: PatchedCognitoAuthConfigRequest | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    provider_id: value.providerId,
    region: value.region,
    user_pool_id: value.userPoolId,
    app_client_id: value.appClientId,
  }
}
