/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface PatchedTeamDetailRequest
 */
export interface PatchedTeamDetailRequest {
  /**
   *
   * @type {string}
   * @memberof PatchedTeamDetailRequest
   */
  name?: string
  /**
   *
   * @type {boolean}
   * @memberof PatchedTeamDetailRequest
   */
  isFreeTrialUsed?: boolean
}

export function PatchedTeamDetailRequestFromJSON(
  json: any
): PatchedTeamDetailRequest {
  return PatchedTeamDetailRequestFromJSONTyped(json, false)
}

export function PatchedTeamDetailRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PatchedTeamDetailRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    name: !exists(json, 'name') ? undefined : json['name'],
    isFreeTrialUsed: !exists(json, 'is_free_trial_used')
      ? undefined
      : json['is_free_trial_used'],
  }
}

export function PatchedTeamDetailRequestToJSON(
  value?: PatchedTeamDetailRequest | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    name: value.name,
    is_free_trial_used: value.isFreeTrialUsed,
  }
}
