/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface PlanContactFormRequest
 */
export interface PlanContactFormRequest {
  /**
   *
   * @type {string}
   * @memberof PlanContactFormRequest
   */
  email?: string
  /**
   *
   * @type {string}
   * @memberof PlanContactFormRequest
   */
  companyName?: string
}

export function PlanContactFormRequestFromJSON(
  json: any
): PlanContactFormRequest {
  return PlanContactFormRequestFromJSONTyped(json, false)
}

export function PlanContactFormRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): PlanContactFormRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    email: !exists(json, 'email') ? undefined : json['email'],
    companyName: !exists(json, 'company_name')
      ? undefined
      : json['company_name'],
  }
}

export function PlanContactFormRequestToJSON(
  value?: PlanContactFormRequest | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    email: value.email,
    company_name: value.companyName,
  }
}
