/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  AuthIssuerEnum,
  AuthIssuerEnumFromJSON,
  AuthIssuerEnumFromJSONTyped,
  AuthIssuerEnumToJSON,
} from './'

/**
 *
 * @export
 * @interface ProviderRequest
 */
export interface ProviderRequest {
  /**
   *
   * @type {string}
   * @memberof ProviderRequest
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof ProviderRequest
   */
  slug: string
  /**
   *
   * @type {string}
   * @memberof ProviderRequest
   */
  authUrl?: string | null
  /**
   *
   * @type {string}
   * @memberof ProviderRequest
   */
  homeUrl?: string | null
  /**
   *
   * @type {string}
   * @memberof ProviderRequest
   */
  webhookUrl?: string | null
  /**
   *
   * @type {string}
   * @memberof ProviderRequest
   */
  invoiceLogoUrl?: string | null
  /**
   *
   * @type {string}
   * @memberof ProviderRequest
   */
  defaultPlanId?: string | null
  /**
   *
   * @type {number}
   * @memberof ProviderRequest
   */
  trialDays?: number
  /**
   *
   * @type {boolean}
   * @memberof ProviderRequest
   */
  isCardRequired?: boolean
  /**
   *
   * @type {string}
   * @memberof ProviderRequest
   */
  supportEmail?: string | null
  /**
   *
   * @type {AuthIssuerEnum}
   * @memberof ProviderRequest
   */
  authIssuer?: AuthIssuerEnum
}

export function ProviderRequestFromJSON(json: any): ProviderRequest {
  return ProviderRequestFromJSONTyped(json, false)
}

export function ProviderRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ProviderRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    name: json['name'],
    slug: json['slug'],
    authUrl: !exists(json, 'auth_url') ? undefined : json['auth_url'],
    homeUrl: !exists(json, 'home_url') ? undefined : json['home_url'],
    webhookUrl: !exists(json, 'webhook_url') ? undefined : json['webhook_url'],
    invoiceLogoUrl: !exists(json, 'invoice_logo_url')
      ? undefined
      : json['invoice_logo_url'],
    defaultPlanId: !exists(json, 'default_plan_id')
      ? undefined
      : json['default_plan_id'],
    trialDays: !exists(json, 'trial_days') ? undefined : json['trial_days'],
    isCardRequired: !exists(json, 'is_card_required')
      ? undefined
      : json['is_card_required'],
    supportEmail: !exists(json, 'support_email')
      ? undefined
      : json['support_email'],
    authIssuer: !exists(json, 'auth_issuer')
      ? undefined
      : AuthIssuerEnumFromJSON(json['auth_issuer']),
  }
}

export function ProviderRequestToJSON(value?: ProviderRequest | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    name: value.name,
    slug: value.slug,
    auth_url: value.authUrl,
    home_url: value.homeUrl,
    webhook_url: value.webhookUrl,
    invoice_logo_url: value.invoiceLogoUrl,
    default_plan_id: value.defaultPlanId,
    trial_days: value.trialDays,
    is_card_required: value.isCardRequired,
    support_email: value.supportEmail,
    auth_issuer: AuthIssuerEnumToJSON(value.authIssuer),
  }
}
