/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  AuthIssuerEnum,
  AuthIssuerEnumFromJSON,
  AuthIssuerEnumFromJSONTyped,
  AuthIssuerEnumToJSON,
  CognitoAuthConfig,
  CognitoAuthConfigFromJSON,
  CognitoAuthConfigFromJSONTyped,
  CognitoAuthConfigToJSON,
  FronteggAuthConfig,
  FronteggAuthConfigFromJSON,
  FronteggAuthConfigFromJSONTyped,
  FronteggAuthConfigToJSON,
  Plan,
  PlanFromJSON,
  PlanFromJSONTyped,
  PlanToJSON,
} from './'

/**
 *
 * @export
 * @interface Provider
 */
export interface Provider {
  /**
   *
   * @type {string}
   * @memberof Provider
   */
  readonly id: string
  /**
   *
   * @type {string}
   * @memberof Provider
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof Provider
   */
  slug: string
  /**
   *
   * @type {string}
   * @memberof Provider
   */
  authUrl?: string | null
  /**
   *
   * @type {string}
   * @memberof Provider
   */
  homeUrl?: string | null
  /**
   *
   * @type {string}
   * @memberof Provider
   */
  webhookUrl?: string | null
  /**
   *
   * @type {string}
   * @memberof Provider
   */
  invoiceLogoUrl?: string | null
  /**
   *
   * @type {Plan}
   * @memberof Provider
   */
  readonly defaultPlan: Plan | null
  /**
   *
   * @type {string}
   * @memberof Provider
   */
  defaultPlanId?: string | null
  /**
   *
   * @type {number}
   * @memberof Provider
   */
  trialDays?: number
  /**
   *
   * @type {boolean}
   * @memberof Provider
   */
  isCardRequired?: boolean
  /**
   *
   * @type {string}
   * @memberof Provider
   */
  readonly ownerId: string
  /**
   *
   * @type {string}
   * @memberof Provider
   */
  readonly stripeAccountId: string
  /**
   *
   * @type {string}
   * @memberof Provider
   */
  readonly shadowId: string | null
  /**
   *
   * @type {string}
   * @memberof Provider
   */
  readonly parentId: string | null
  /**
   *
   * @type {boolean}
   * @memberof Provider
   */
  readonly isShadow: boolean
  /**
   *
   * @type {string}
   * @memberof Provider
   */
  supportEmail?: string | null
  /**
   *
   * @type {AuthIssuerEnum}
   * @memberof Provider
   */
  authIssuer?: AuthIssuerEnum
  /**
   *
   * @type {CognitoAuthConfig}
   * @memberof Provider
   */
  readonly cognitoAuthConfig: CognitoAuthConfig | null
  /**
   *
   * @type {FronteggAuthConfig}
   * @memberof Provider
   */
  readonly fronteggAuthConfig: FronteggAuthConfig | null
}

export function ProviderFromJSON(json: any): Provider {
  return ProviderFromJSONTyped(json, false)
}

export function ProviderFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Provider {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: json['id'],
    name: json['name'],
    slug: json['slug'],
    authUrl: !exists(json, 'auth_url') ? undefined : json['auth_url'],
    homeUrl: !exists(json, 'home_url') ? undefined : json['home_url'],
    webhookUrl: !exists(json, 'webhook_url') ? undefined : json['webhook_url'],
    invoiceLogoUrl: !exists(json, 'invoice_logo_url')
      ? undefined
      : json['invoice_logo_url'],
    defaultPlan: PlanFromJSON(json['default_plan']),
    defaultPlanId: !exists(json, 'default_plan_id')
      ? undefined
      : json['default_plan_id'],
    trialDays: !exists(json, 'trial_days') ? undefined : json['trial_days'],
    isCardRequired: !exists(json, 'is_card_required')
      ? undefined
      : json['is_card_required'],
    ownerId: json['owner_id'],
    stripeAccountId: json['stripe_account_id'],
    shadowId: json['shadow_id'],
    parentId: json['parent_id'],
    isShadow: json['is_shadow'],
    supportEmail: !exists(json, 'support_email')
      ? undefined
      : json['support_email'],
    authIssuer: !exists(json, 'auth_issuer')
      ? undefined
      : AuthIssuerEnumFromJSON(json['auth_issuer']),
    cognitoAuthConfig: CognitoAuthConfigFromJSON(json['cognito_auth_config']),
    fronteggAuthConfig: FronteggAuthConfigFromJSON(
      json['frontegg_auth_config']
    ),
  }
}

export function ProviderToJSON(value?: Provider | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    name: value.name,
    slug: value.slug,
    auth_url: value.authUrl,
    home_url: value.homeUrl,
    webhook_url: value.webhookUrl,
    invoice_logo_url: value.invoiceLogoUrl,
    default_plan_id: value.defaultPlanId,
    trial_days: value.trialDays,
    is_card_required: value.isCardRequired,
    support_email: value.supportEmail,
    auth_issuer: AuthIssuerEnumToJSON(value.authIssuer),
  }
}
