/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum RequirementsEnum {
  PaymentMethodSaved = 'payment_method_saved',
}

export function RequirementsEnumFromJSON(json: any): RequirementsEnum {
  return RequirementsEnumFromJSONTyped(json, false)
}

export function RequirementsEnumFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): RequirementsEnum {
  return json as RequirementsEnum
}

export function RequirementsEnumToJSON(value?: RequirementsEnum | null): any {
  return value as any
}
