/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum RequirementsMetEnum {
  PaymentMethodSaved = 'payment_method_saved',
}

export function RequirementsMetEnumFromJSON(json: any): RequirementsMetEnum {
  return RequirementsMetEnumFromJSONTyped(json, false)
}

export function RequirementsMetEnumFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): RequirementsMetEnum {
  return json as RequirementsMetEnum
}

export function RequirementsMetEnumToJSON(
  value?: RequirementsMetEnum | null
): any {
  return value as any
}
