/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface SetupIntentConfirmRequest
 */
export interface SetupIntentConfirmRequest {
  /**
   *
   * @type {string}
   * @memberof SetupIntentConfirmRequest
   */
  stripeSetupId: string
}

export function SetupIntentConfirmRequestFromJSON(
  json: any
): SetupIntentConfirmRequest {
  return SetupIntentConfirmRequestFromJSONTyped(json, false)
}

export function SetupIntentConfirmRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SetupIntentConfirmRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    stripeSetupId: json['stripe_setup_id'],
  }
}

export function SetupIntentConfirmRequestToJSON(
  value?: SetupIntentConfirmRequest | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    stripe_setup_id: value.stripeSetupId,
  }
}
