/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  SILineItemRequest,
  SILineItemRequestFromJSON,
  SILineItemRequestFromJSONTyped,
  SILineItemRequestToJSON,
  StateEnum,
  StateEnumFromJSON,
  StateEnumFromJSONTyped,
  StateEnumToJSON,
} from './'

/**
 *
 * @export
 * @interface SIInvoiceRequest
 */
export interface SIInvoiceRequest {
  /**
   *
   * @type {string}
   * @memberof SIInvoiceRequest
   */
  id: string
  /**
   *
   * @type {StateEnum}
   * @memberof SIInvoiceRequest
   */
  state: StateEnum
  /**
   *
   * @type {number}
   * @memberof SIInvoiceRequest
   */
  cents: number
  /**
   *
   * @type {Array<SILineItemRequest>}
   * @memberof SIInvoiceRequest
   */
  lineItems: Array<SILineItemRequest>
}

export function SIInvoiceRequestFromJSON(json: any): SIInvoiceRequest {
  return SIInvoiceRequestFromJSONTyped(json, false)
}

export function SIInvoiceRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SIInvoiceRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: json['id'],
    state: StateEnumFromJSON(json['state']),
    cents: json['cents'],
    lineItems: (json['line_items'] as Array<any>).map(
      SILineItemRequestFromJSON
    ),
  }
}

export function SIInvoiceRequestToJSON(value?: SIInvoiceRequest | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    state: StateEnumToJSON(value.state),
    cents: value.cents,
    line_items: (value.lineItems as Array<any>).map(SILineItemRequestToJSON),
  }
}
