/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface SILineItemRequest
 */
export interface SILineItemRequest {
  /**
   *
   * @type {string}
   * @memberof SILineItemRequest
   */
  title: string
  /**
   *
   * @type {string}
   * @memberof SILineItemRequest
   */
  detail: string
  /**
   *
   * @type {number}
   * @memberof SILineItemRequest
   */
  cents: number
}

export function SILineItemRequestFromJSON(json: any): SILineItemRequest {
  return SILineItemRequestFromJSONTyped(json, false)
}

export function SILineItemRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SILineItemRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    title: json['title'],
    detail: json['detail'],
    cents: json['cents'],
  }
}

export function SILineItemRequestToJSON(value?: SILineItemRequest | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    title: value.title,
    detail: value.detail,
    cents: value.cents,
  }
}
