/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface StripeCard
 */
export interface StripeCard {
  /**
   *
   * @type {string}
   * @memberof StripeCard
   */
  readonly brand: string
  /**
   *
   * @type {string}
   * @memberof StripeCard
   */
  readonly last4: string
  /**
   *
   * @type {number}
   * @memberof StripeCard
   */
  readonly expMonth: number
  /**
   *
   * @type {number}
   * @memberof StripeCard
   */
  readonly expYear: number
}

export function StripeCardFromJSON(json: any): StripeCard {
  return StripeCardFromJSONTyped(json, false)
}

export function StripeCardFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): StripeCard {
  if (json === undefined || json === null) {
    return json
  }
  return {
    brand: json['brand'],
    last4: json['last4'],
    expMonth: json['exp_month'],
    expYear: json['exp_year'],
  }
}

export function StripeCardToJSON(value?: StripeCard | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {}
}
