/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  ButtonFieldRequest,
  ButtonFieldRequestFromJSON,
  ButtonFieldRequestFromJSONTyped,
  ButtonFieldRequestToJSON,
  RequirementsEnum,
  RequirementsEnumFromJSON,
  RequirementsEnumFromJSONTyped,
  RequirementsEnumToJSON,
  RequirementsMetEnum,
  RequirementsMetEnumFromJSON,
  RequirementsMetEnumFromJSONTyped,
  RequirementsMetEnumToJSON,
} from './'

/**
 * Base serializer for all actions.
 * @export
 * @interface SubscribeActionRequest
 */
export interface SubscribeActionRequest {
  /**
   *
   * @type {ButtonFieldRequest}
   * @memberof SubscribeActionRequest
   */
  button?: ButtonFieldRequest
  /**
   *
   * @type {Array<RequirementsEnum>}
   * @memberof SubscribeActionRequest
   */
  requirements: Array<RequirementsEnum>
  /**
   *
   * @type {Array<RequirementsMetEnum>}
   * @memberof SubscribeActionRequest
   */
  requirementsMet: Array<RequirementsMetEnum>
}

export function SubscribeActionRequestFromJSON(
  json: any
): SubscribeActionRequest {
  return SubscribeActionRequestFromJSONTyped(json, false)
}

export function SubscribeActionRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SubscribeActionRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    button: !exists(json, 'button')
      ? undefined
      : ButtonFieldRequestFromJSON(json['button']),
    requirements: (json['requirements'] as Array<any>).map(
      RequirementsEnumFromJSON
    ),
    requirementsMet: (json['requirements_met'] as Array<any>).map(
      RequirementsMetEnumFromJSON
    ),
  }
}

export function SubscribeActionRequestToJSON(
  value?: SubscribeActionRequest | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    button: ButtonFieldRequestToJSON(value.button),
    requirements: (value.requirements as Array<any>).map(
      RequirementsEnumToJSON
    ),
    requirements_met: (value.requirementsMet as Array<any>).map(
      RequirementsMetEnumToJSON
    ),
  }
}
