/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  OnSubscriptionEndEnum,
  OnSubscriptionEndEnumFromJSON,
  OnSubscriptionEndEnumFromJSONTyped,
  OnSubscriptionEndEnumToJSON,
  SIInvoiceRequest,
  SIInvoiceRequestFromJSON,
  SIInvoiceRequestFromJSONTyped,
  SIInvoiceRequestToJSON,
} from './'

/**
 *
 * @export
 * @interface SubscribeIntentRequest
 */
export interface SubscribeIntentRequest {
  /**
   *
   * @type {string}
   * @memberof SubscribeIntentRequest
   */
  id: string
  /**
   *
   * @type {string}
   * @memberof SubscribeIntentRequest
   */
  planOptionId: string
  /**
   *
   * @type {SIInvoiceRequest}
   * @memberof SubscribeIntentRequest
   */
  invoice: SIInvoiceRequest
  /**
   *
   * @type {number}
   * @memberof SubscribeIntentRequest
   */
  creditCents: number
  /**
   *
   * @type {OnSubscriptionEndEnum}
   * @memberof SubscribeIntentRequest
   */
  onSubscriptionEnd: OnSubscriptionEndEnum
  /**
   *
   * @type {number}
   * @memberof SubscribeIntentRequest
   */
  nextUpfrontBillInDays: number
  /**
   *
   * @type {number}
   * @memberof SubscribeIntentRequest
   */
  nextMeterBillInDays: number
  /**
   *
   * @type {number}
   * @memberof SubscribeIntentRequest
   */
  trialEndInDays: number
}

export function SubscribeIntentRequestFromJSON(
  json: any
): SubscribeIntentRequest {
  return SubscribeIntentRequestFromJSONTyped(json, false)
}

export function SubscribeIntentRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SubscribeIntentRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: json['id'],
    planOptionId: json['plan_option_id'],
    invoice: SIInvoiceRequestFromJSON(json['invoice']),
    creditCents: json['credit_cents'],
    onSubscriptionEnd: OnSubscriptionEndEnumFromJSON(
      json['on_subscription_end']
    ),
    nextUpfrontBillInDays: json['next_upfront_bill_in_days'],
    nextMeterBillInDays: json['next_meter_bill_in_days'],
    trialEndInDays: json['trial_end_in_days'],
  }
}

export function SubscribeIntentRequestToJSON(
  value?: SubscribeIntentRequest | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    plan_option_id: value.planOptionId,
    invoice: SIInvoiceRequestToJSON(value.invoice),
    credit_cents: value.creditCents,
    on_subscription_end: OnSubscriptionEndEnumToJSON(value.onSubscriptionEnd),
    next_upfront_bill_in_days: value.nextUpfrontBillInDays,
    next_meter_bill_in_days: value.nextMeterBillInDays,
    trial_end_in_days: value.trialEndInDays,
  }
}
