/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  OnSubscriptionEndEnum,
  OnSubscriptionEndEnumFromJSON,
  OnSubscriptionEndEnumFromJSONTyped,
  OnSubscriptionEndEnumToJSON,
  SIInvoice,
  SIInvoiceFromJSON,
  SIInvoiceFromJSONTyped,
  SIInvoiceToJSON,
} from './'

/**
 *
 * @export
 * @interface SubscribeIntent
 */
export interface SubscribeIntent {
  /**
   *
   * @type {string}
   * @memberof SubscribeIntent
   */
  id: string
  /**
   *
   * @type {string}
   * @memberof SubscribeIntent
   */
  planOptionId: string
  /**
   *
   * @type {SIInvoice}
   * @memberof SubscribeIntent
   */
  invoice: SIInvoice
  /**
   *
   * @type {number}
   * @memberof SubscribeIntent
   */
  creditCents: number
  /**
   *
   * @type {OnSubscriptionEndEnum}
   * @memberof SubscribeIntent
   */
  onSubscriptionEnd: OnSubscriptionEndEnum
  /**
   *
   * @type {number}
   * @memberof SubscribeIntent
   */
  nextUpfrontBillInDays: number
  /**
   *
   * @type {number}
   * @memberof SubscribeIntent
   */
  nextMeterBillInDays: number
  /**
   *
   * @type {number}
   * @memberof SubscribeIntent
   */
  trialEndInDays: number
}

export function SubscribeIntentFromJSON(json: any): SubscribeIntent {
  return SubscribeIntentFromJSONTyped(json, false)
}

export function SubscribeIntentFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SubscribeIntent {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: json['id'],
    planOptionId: json['plan_option_id'],
    invoice: SIInvoiceFromJSON(json['invoice']),
    creditCents: json['credit_cents'],
    onSubscriptionEnd: OnSubscriptionEndEnumFromJSON(
      json['on_subscription_end']
    ),
    nextUpfrontBillInDays: json['next_upfront_bill_in_days'],
    nextMeterBillInDays: json['next_meter_bill_in_days'],
    trialEndInDays: json['trial_end_in_days'],
  }
}

export function SubscribeIntentToJSON(value?: SubscribeIntent | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    id: value.id,
    plan_option_id: value.planOptionId,
    invoice: SIInvoiceToJSON(value.invoice),
    credit_cents: value.creditCents,
    on_subscription_end: OnSubscriptionEndEnumToJSON(value.onSubscriptionEnd),
    next_upfront_bill_in_days: value.nextUpfrontBillInDays,
    next_meter_bill_in_days: value.nextMeterBillInDays,
    trial_end_in_days: value.trialEndInDays,
  }
}
