/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface Subscription
 */
export interface Subscription {
  /**
   *
   * @type {string}
   * @memberof Subscription
   */
  readonly id: string
  /**
   *
   * @type {string}
   * @memberof Subscription
   */
  planId: string
  /**
   *
   * @type {string}
   * @memberof Subscription
   */
  teamId: string
  /**
   *
   * @type {Date}
   * @memberof Subscription
   */
  readonly startAt: Date
  /**
   *
   * @type {Date}
   * @memberof Subscription
   */
  readonly endAt: Date | null
  /**
   *
   * @type {Date}
   * @memberof Subscription
   */
  freeTrialEndAt?: Date | null
  /**
   *
   * @type {boolean}
   * @memberof Subscription
   */
  isPaused?: boolean
  /**
   *
   * @type {boolean}
   * @memberof Subscription
   */
  readonly isActive: boolean
  /**
   *
   * @type {string}
   * @memberof Subscription
   */
  nextPlanId?: string
  /**
   *
   * @type {Date}
   * @memberof Subscription
   */
  cancelOn?: Date | null
}

export function SubscriptionFromJSON(json: any): Subscription {
  return SubscriptionFromJSONTyped(json, false)
}

export function SubscriptionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): Subscription {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: json['id'],
    planId: json['plan_id'],
    teamId: json['team_id'],
    startAt: new Date(json['start_at']),
    endAt: json['end_at'] === null ? null : new Date(json['end_at']),
    freeTrialEndAt: !exists(json, 'free_trial_end_at')
      ? undefined
      : json['free_trial_end_at'] === null
      ? null
      : new Date(json['free_trial_end_at']),
    isPaused: !exists(json, 'is_paused') ? undefined : json['is_paused'],
    isActive: json['is_active'],
    nextPlanId: !exists(json, 'next_plan_id')
      ? undefined
      : json['next_plan_id'],
    cancelOn: !exists(json, 'cancel_on')
      ? undefined
      : json['cancel_on'] === null
      ? null
      : new Date(json['cancel_on']),
  }
}

export function SubscriptionToJSON(value?: Subscription | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    plan_id: value.planId,
    team_id: value.teamId,
    free_trial_end_at:
      value.freeTrialEndAt === undefined
        ? undefined
        : value.freeTrialEndAt === null
        ? null
        : value.freeTrialEndAt.toISOString(),
    is_paused: value.isPaused,
    next_plan_id: value.nextPlanId,
    cancel_on:
      value.cancelOn === undefined
        ? undefined
        : value.cancelOn === null
        ? null
        : value.cancelOn.toISOString(),
  }
}
