/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  ButtonField,
  ButtonFieldFromJSON,
  ButtonFieldFromJSONTyped,
  ButtonFieldToJSON,
  RequirementsEnum,
  RequirementsEnumFromJSON,
  RequirementsEnumFromJSONTyped,
  RequirementsEnumToJSON,
  RequirementsMetEnum,
  RequirementsMetEnumFromJSON,
  RequirementsMetEnumFromJSONTyped,
  RequirementsMetEnumToJSON,
} from './'

/**
 * Base serializer for all actions.
 * @export
 * @interface SubscribeAction
 */
export interface SubscribeAction {
  /**
   *
   * @type {Array<RequirementsEnum>}
   * @memberof SubscribeAction
   */
  requirements: Array<RequirementsEnum>
  /**
   *
   * @type {Array<RequirementsMetEnum>}
   * @memberof SubscribeAction
   */
  requirementsMet: Array<RequirementsMetEnum>
  /**
   *
   * @type {ButtonField}
   * @memberof SubscribeAction
   */
  button: ButtonField
}

export function SubscribeActionFromJSON(json: any): SubscribeAction {
  return SubscribeActionFromJSONTyped(json, false)
}

export function SubscribeActionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): SubscribeAction {
  if (json === undefined || json === null) {
    return json
  }
  return {
    requirements: (json['requirements'] as Array<any>).map(
      RequirementsEnumFromJSON
    ),
    requirementsMet: (json['requirements_met'] as Array<any>).map(
      RequirementsMetEnumFromJSON
    ),
    button: ButtonFieldFromJSON(json['button']),
  }
}

export function SubscribeActionToJSON(value?: SubscribeAction | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    requirements: (value.requirements as Array<any>).map(
      RequirementsEnumToJSON
    ),
    requirements_met: (value.requirementsMet as Array<any>).map(
      RequirementsMetEnumToJSON
    ),
    button: ButtonFieldToJSON(value.button),
  }
}
