/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface TeamMetadataRequest
 */
export interface TeamMetadataRequest {
  /**
   *
   * @type {string}
   * @memberof TeamMetadataRequest
   */
  key: string
  /**
   *
   * @type {string}
   * @memberof TeamMetadataRequest
   */
  value: string
}

export function TeamMetadataRequestFromJSON(json: any): TeamMetadataRequest {
  return TeamMetadataRequestFromJSONTyped(json, false)
}

export function TeamMetadataRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): TeamMetadataRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    key: json['key'],
    value: json['value'],
  }
}

export function TeamMetadataRequestToJSON(
  value?: TeamMetadataRequest | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    key: value.key,
    value: value.value,
  }
}
