/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface TeamViaMembership
 */
export interface TeamViaMembership {
  /**
   *
   * @type {string}
   * @memberof TeamViaMembership
   */
  readonly id: string
  /**
   *
   * @type {string}
   * @memberof TeamViaMembership
   */
  readonly name: string
}

export function TeamViaMembershipFromJSON(json: any): TeamViaMembership {
  return TeamViaMembershipFromJSONTyped(json, false)
}

export function TeamViaMembershipFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): TeamViaMembership {
  if (json === undefined || json === null) {
    return json
  }
  return {
    id: json['id'],
    name: json['name'],
  }
}

export function TeamViaMembershipToJSON(value?: TeamViaMembership | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {}
}
