/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import {
  ButtonField,
  ButtonFieldFromJSON,
  ButtonFieldFromJSONTyped,
  ButtonFieldToJSON,
} from './'

/**
 * Base serializer for all actions.
 * @export
 * @interface UndoCancelAction
 */
export interface UndoCancelAction {
  /**
   *
   * @type {ButtonField}
   * @memberof UndoCancelAction
   */
  button?: ButtonField
  /**
   *
   * @type {string}
   * @memberof UndoCancelAction
   */
  subscriptionId?: string
}

export function UndoCancelActionFromJSON(json: any): UndoCancelAction {
  return UndoCancelActionFromJSONTyped(json, false)
}

export function UndoCancelActionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UndoCancelAction {
  if (json === undefined || json === null) {
    return json
  }
  return {
    button: !exists(json, 'button')
      ? undefined
      : ButtonFieldFromJSON(json['button']),
    subscriptionId: !exists(json, 'subscription_id')
      ? undefined
      : json['subscription_id'],
  }
}

export function UndoCancelActionToJSON(value?: UndoCancelAction | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    button: ButtonFieldToJSON(value.button),
    subscription_id: value.subscriptionId,
  }
}
