/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface UpdatePaymentMethodRequest
 */
export interface UpdatePaymentMethodRequest {
  /**
   *
   * @type {boolean}
   * @memberof UpdatePaymentMethodRequest
   */
  isDefault?: boolean | null
}

export function UpdatePaymentMethodRequestFromJSON(
  json: any
): UpdatePaymentMethodRequest {
  return UpdatePaymentMethodRequestFromJSONTyped(json, false)
}

export function UpdatePaymentMethodRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UpdatePaymentMethodRequest {
  if (json === undefined || json === null) {
    return json
  }
  return {
    isDefault: !exists(json, 'is_default') ? undefined : json['is_default'],
  }
}

export function UpdatePaymentMethodRequestToJSON(
  value?: UpdatePaymentMethodRequest | null
): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    is_default: value.isDefault,
  }
}
