/* tslint:disable */
/* eslint-disable */
/**
 * Iron Plans API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface UsageExceeded
 */
export interface UsageExceeded {
  /**
   *
   * @type {boolean}
   * @memberof UsageExceeded
   */
  exceeded: boolean
}

export function UsageExceededFromJSON(json: any): UsageExceeded {
  return UsageExceededFromJSONTyped(json, false)
}

export function UsageExceededFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): UsageExceeded {
  if (json === undefined || json === null) {
    return json
  }
  return {
    exceeded: json['exceeded'],
  }
}

export function UsageExceededToJSON(value?: UsageExceeded | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    exceeded: value.exceeded,
  }
}
